apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-scaffold.fullname" . }}
  labels:
  {{- include "go-scaffold.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}